// civs.js

export const CIVS = {
  "Aztecs": { roles: ["infantry", "siege"], mobility: 1, siege: 3, cav: 0 },
  "Bengalis": { roles: ["elephant", "defensive"], mobility: 1, siege: 2, cav: 1 },
  "Berbers": { roles: ["cavalry", "mobility"], mobility: 3, siege: 1, cav: 3 },
  "Bohemians": { roles: ["gunpowder", "siege"], mobility: 1, siege: 3, cav: 0 },
  "Britons": { roles: ["archer"], mobility: 1, siege: 2, cav: 0 },
  "Bulgarians": { roles: ["infantry", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Burgundians": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Burmese": { roles: ["infantry"], mobility: 1, siege: 1, cav: 2 },
  "Byzantines": { roles: ["defensive", "counter"], mobility: 1, siege: 2, cav: 1 },
  "Celts": { roles: ["infantry", "siege"], mobility: 1, siege: 3, cav: 0 },
  "Chinese": { roles: ["archer"], mobility: 1, siege: 2, cav: 1 },
  "Cumans": { roles: ["cavalry", "mobility"], mobility: 3, siege: 1, cav: 3 },
  "Dravidians": { roles: ["infantry", "siege"], mobility: 1, siege: 2, cav: 0 },
  "Ethiopians": { roles: ["archer", "siege"], mobility: 1, siege: 2, cav: 0 },
  "Franks": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Georgians": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Goths": { roles: ["infantry"], mobility: 1, siege: 1, cav: 0 },
  "Gurjaras": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Hindustanis": { roles: ["gunpowder", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Huns": { roles: ["cavalry", "mobility"], mobility: 3, siege: 1, cav: 3 },
  "Incas": { roles: ["infantry"], mobility: 1, siege: 1, cav: 0 },
  "Italians": { roles: ["archer", "gunpowder"], mobility: 1, siege: 1, cav: 0 },
  "Japanese": { roles: ["infantry"], mobility: 1, siege: 1, cav: 0 },
  "Khmer": { roles: ["elephant", "siege"], mobility: 2, siege: 2, cav: 2 },
  "Koreans": { roles: ["defensive", "siege"], mobility: 1, siege: 3, cav: 0 },
  "Lithuanians": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Magyars": { roles: ["cavalry", "mobility"], mobility: 3, siege: 1, cav: 3 },
  "Malay": { roles: ["naval"], mobility: 1, siege: 1, cav: 0 },
  "Malians": { roles: ["infantry", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Mayans": { roles: ["archer"], mobility: 1, siege: 1, cav: 0 },
  "Mongols": { roles: ["cavalry", "mobility"], mobility: 3, siege: 2, cav: 3 },
  "Persians": { roles: ["cavalry"], mobility: 2, siege: 2, cav: 3 },
  "Poles": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Portuguese": { roles: ["gunpowder"], mobility: 1, siege: 1, cav: 0 },
  "Romans": { roles: ["infantry"], mobility: 1, siege: 2, cav: 1 },
  "Saracens": { roles: ["archer", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Sicilians": { roles: ["cavalry"], mobility: 2, siege: 1, cav: 3 },
  "Slavs": { roles: ["infantry", "siege"], mobility: 1, siege: 3, cav: 0 },
  "Spanish": { roles: ["gunpowder", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Tatars": { roles: ["cavalry", "mobility"], mobility: 3, siege: 1, cav: 3 },
  "Teutons": { roles: ["defensive", "infantry"], mobility: 0, siege: 2, cav: 2 },
  "Turks": { roles: ["gunpowder", "cavalry"], mobility: 2, siege: 1, cav: 2 },
  "Vietnamese": { roles: ["archer"], mobility: 1, siege: 1, cav: 0 },
  "Vikings": { roles: ["infantry"], mobility: 1, siege: 1, cav: 0 }
};
