console.log("civs.js loaded");

const civs = {
  "Armenians":      { siege:3, cav:3, mobility:2, archer:3, eco:3, antiCav:2, antiArcher:2, antiInf:2 },
  "Aztecs":         { siege:3, cav:1, mobility:2, archer:2, eco:4, antiCav:4, antiArcher:3, antiInf:3 },
  "Bengalis":       { siege:3, cav:3, mobility:2, archer:3, eco:3, antiCav:3, antiArcher:3, antiInf:2 },
  "Berbers":        { siege:3, cav:5, mobility:5, archer:3, eco:3, antiCav:3, antiArcher:2, antiInf:2 },
  "Bohemians":      { siege:5, cav:2, mobility:2, archer:4, eco:3, antiCav:5, antiArcher:3, antiInf:4 },
  "Britons":        { siege:2, cav:2, mobility:2, archer:5, eco:3, antiCav:2, antiArcher:5, antiInf:2 },
  "Bulgarians":     { siege:4, cav:4, mobility:4, archer:2, eco:3, antiCav:3, antiArcher:2, antiInf:4 },
  "Burgundians":    { siege:3, cav:5, mobility:4, archer:2, eco:4, antiCav:3, antiArcher:2, antiInf:3 },
  "Burmese":        { siege:3, cav:3, mobility:2, archer:2, eco:3, antiCav:3, antiArcher:2, antiInf:4 },
  "Byzantines":     { siege:3, cav:3, mobility:3, archer:3, eco:3, antiCav:5, antiArcher:4, antiInf:4 },
  "Celts":          { siege:5, cav:2, mobility:3, archer:2, eco:3, antiCav:2, antiArcher:2, antiInf:4 },
  "Chinese":        { siege:3, cav:3, mobility:3, archer:4, eco:5, antiCav:3, antiArcher:4, antiInf:3 },
  "Cumans":         { siege:3, cav:4, mobility:5, archer:2, eco:4, antiCav:3, antiArcher:2, antiInf:2 },
  "Dravidians":     { siege:3, cav:1, mobility:2, archer:4, eco:3, antiCav:4, antiArcher:3, antiInf:4 },
  "Ethiopians":     { siege:4, cav:2, mobility:3, archer:5, eco:3, antiCav:3, antiArcher:4, antiInf:3 },
  "Franks":         { siege:3, cav:5, mobility:4, archer:2, eco:4, antiCav:4, antiArcher:2, antiInf:3 },
  "Georgians":      { siege:3, cav:4, mobility:4, archer:3, eco:3, antiCav:3, antiArcher:3, antiInf:3 },
  "Goths":          { siege:2, cav:1, mobility:2, archer:1, eco:3, antiCav:3, antiArcher:2, antiInf:5 },
  "Gurjaras":       { siege:3, cav:5, mobility:5, archer:2, eco:3, antiCav:4, antiArcher:2, antiInf:3 },
  "Hindustanis":    { siege:3, cav:3, mobility:3, archer:3, eco:4, antiCav:4, antiArcher:3, antiInf:3 },
  "Huns":           { siege:3, cav:5, mobility:5, archer:3, eco:4, antiCav:3, antiArcher:3, antiInf:2 },
  "Incas":          { siege:3, cav:1, mobility:2, archer:3, eco:4, antiCav:5, antiArcher:3, antiInf:4 },
  "Italians":       { siege:3, cav:2, mobility:3, archer:4, eco:3, antiCav:3, antiArcher:4, antiInf:2 },
  "Japanese":       { siege:3, cav:2, mobility:3, archer:3, eco:3, antiCav:4, antiArcher:3, antiInf:4 },
  "Khmer":          { siege:4, cav:4, mobility:4, archer:3, eco:4, antiCav:3, antiArcher:2, antiInf:3 },
  "Koreans":        { siege:4, cav:1, mobility:2, archer:5, eco:3, antiCav:3, antiArcher:5, antiInf:2 },
  "Lithuanians":    { siege:3, cav:5, mobility:4, archer:2, eco:4, antiCav:4, antiArcher:2, antiInf:3 },
  "Magyars":        { siege:3, cav:5, mobility:5, archer:3, eco:3, antiCav:3, antiArcher:3, antiInf:2 },
  "Malians":        { siege:3, cav:3, mobility:3, archer:3, eco:4, antiCav:4, antiArcher:3, antiInf:4 },
  "Maya":           { siege:2, cav:1, mobility:3, archer:5, eco:4, antiCav:3, antiArcher:5, antiInf:2 },
  "Mongols":        { siege:4, cav:5, mobility:5, archer:4, eco:3, antiCav:3, antiArcher:3, antiInf:2 },
  "Persians":       { siege:3, cav:5, mobility:4, archer:2, eco:4, antiCav:4, antiArcher:2, antiInf:3 },
  "Poles":          { siege:3, cav:5, mobility:4, archer:2, eco:4, antiCav:3, antiArcher:2, antiInf:3 },
  "Portuguese":     { siege:4, cav:2, mobility:3, archer:4, eco:4, antiCav:3, antiArcher:4, antiInf:3 },
  "Romans":         { siege:4, cav:3, mobility:3, archer:3, eco:3, antiCav:3, antiArcher:3, antiInf:4 },
  "Saracens":       { siege:4, cav:4, mobility:4, archer:4, eco:3, antiCav:3, antiArcher:3, antiInf:3 },
  "Sicilians":      { siege:3, cav:4, mobility:3, archer:2, eco:3, antiCav:4, antiArcher:3, antiInf:4 },
  "Slavs":          { siege:4, cav:4, mobility:3, archer:2, eco:4, antiCav:4, antiArcher:2, antiInf:4 },
  "Spanish":        { siege:4, cav:4, mobility:3, archer:2, eco:3, antiCav:3, antiArcher:3, antiInf:3 },
  "Tatars":         { siege:3, cav:5, mobility:5, archer:4, eco:3, antiCav:3, antiArcher:4, antiInf:2 },
  "Teutons":        { siege:4, cav:3, mobility:2, archer:2, eco:4, antiCav:5, antiArcher:3, antiInf:5 },
  "Turks":          { siege:4, cav:4, mobility:4, archer:4, eco:3, antiCav:3, antiArcher:4, antiInf:2 },
  "Vietnamese":     { siege:3, cav:2, mobility:3, archer:4, eco:4, antiCav:3, antiArcher:4, antiInf:3 },
  "Vikings":        { siege:3, cav:1, mobility:2, archer:3, eco:4, antiCav:4, antiArcher:3, antiInf:4 }
};
